### ISSUE TITLE
MCscanx circle_plotter program and dual_synteny_plotter program can not produce a figure

### ISSUE THREAD

**Issue by taotaoyuan** [wyp1125/MCScanX#22]
![image](https://user-images.githubusercontent.com/54825588/75453924-97412800-59af-11ea-92e5-36d158539471.png)

**Comment by baizixiansheng** [comment]
I also had the problem of circle_plotter, my command is as follow:
`java circle_plotter -g /home/shu/Music/mcscan/data/Cc/A0605/Sty.gff -s Sty.collinearity -c dot2.ctl -o a2.png`
and the erros:
`Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using  localhost:12.0' as the value of the DISPLAY variable.`
	`at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)`
	`at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)`
	`at java.base/java.security.AccessController.doPrivileged(Native Method)`
	`at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)`
	`at java.base/java.lang.Class.forName0(Native Method)`
	`at java.base/java.lang.Class.forName(Class.java:315)`
	`at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)`
	`at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)`
	`at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)`
	`at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)`
	`at circle_plotter.main(circle_plotter.java:261)`
I have no idea to solve this problem, could you help me?
