### ISSUE TITLE
Error in family_tree_plotter

### ISSUE THREAD

**Issue by ashish674675** [wyp1125/MCScanX#23]
Hi
I want to display segmental and tandem duplications in a gene family tree. I ran the following commands :

```
javac family_tree_plotter.java
java family_tree_plotter -t ../../mcscanx_input/tree.nwk -s ../../mcscanx_input/rice.collinearity  –d ../../mcscanx_input/rice.tandem -o tandem_segmental_genes_tree.png
```

I get this error:

```
Exception in thread "main" java.lang.NullPointerException
        at family_tree_plotter.compute(family_tree_plotter.java:263)
        at family_tree_plotter.paint(family_tree_plotter.java:299)
        at family_tree_plotter.main(family_tree_plotter.java:397)

```

Please help me resolve this error. I am doing it on ubuntu in WSL. All other MCScanX commands I ran were successfull except this one.

Thank You

**Comment by ashish674675** [comment]
I found the problem. The tree file had bootstrap values instead of branch lengths which was causing a format problem between ":" and ",".
