### ISSUE TITLE
Reading gff error: For input string: "2147774468"

### ISSUE THREAD

**Issue by limengchen628** [wyp1125/MCScanX#63]
Hello, I used MCScanX to analyze, i've prepared the necessaries files following the manual yet my data and example data. When I use circle_plotter to draw pictures, the example data is working, but my data doesn't work. This is my log data:

 java circle_plotter -g Po.gff -s Po.collinearity -c circle.ctl -o exam3.png
#error message
Reading gff error: For input string: "2147774468"
Exception in thread "main" java.lang.NullPointerException
        at circle_plotter.paint(circle_plotter.java:142)
        at circle_plotter.main(circle_plotter.java:262)

I could not find any other response regarding this problem. Anyone knows what sorcery I must make to put the program to work?

Thanks

**Comment by thesnakeguy** [comment]
How did you even managed to get the .collinearity output from MCScanX. I am using my .blast and .gff (chr gene start stop) as input, but I get 0 matches. Others are reporting the same issue. Your input would help a lot! Cheers

**Comment by cui-yutong** [comment]
I'm having the same issue with MCscanX, it seems that when the sequence length of a chromosome is greater than 2^31=2.14 Gb, the program doesn't recognize it.
How can I do it so that the program can read longer sequence lengths
