### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AndyLy2Zy** [wyp1125/MCScanX#65]
Hi All,

I have got a question when I use the circle_plotter. Is there have any advance?

![image](https://user-images.githubusercontent.com/115370378/218609917-952b5ed9-4c73-4baa-963b-89a8d1848f9f.png)

**Comment by sunying12** [comment]
I got the same error while running a dot plot

Exception in thread "main" java.lang.NullPointerException
	at dot_plotter.paint(dot_plotter.java:163)
	at dot_plotter.main(dot_plotter.java:262)

**Comment by YingyingZ9** [comment]
> I got the same error while running a dot plot
> 
> Exception in thread "main" java.lang.NullPointerException at dot_plotter.paint(dot_plotter.java:163) at dot_plotter.main(dot_plotter.java:262)

**Comment by YingyingZ9** [comment]
> I got the same error while running a dot plot
> 
> Exception in thread "main" java.lang.NullPointerException at dot_plotter.paint(dot_plotter.java:163) at dot_plotter.main(dot_plotter.java:262)

how do you solve this problem ?
